[default]
VERSION = "0.9.0"

[default.jwt]
ACCESS_TOKEN_EXPIRE_MINUTES=10
ALGORITHM="HS256"

[default.server]
URL = "https://spotify.janhendrikewers.uk"
API_PATH = "/api"
PORT = "3001"
IP = "0.0.0.0"
OPENAPI_URL="/openapi.json"
DOCS=true

[default.spotify]
SCOPE = "user-library-read playlist-modify-public playlist-modify-private"

[development]
[development.server]
dynaconf_merge=true
URL = "http://localhost"
API_PATH = ""

VALUE_FOR_TESTING=1

[development.database]
URI = "mongodb://test:test@0.0.0.0:27017/"
DB = "AutonomaDev"

[production]
[production.server]
dynaconf_merge=true
openapi_url=""
DOCS=false

VALUE_FOR_TESTING=2